name: Lint

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]
  workflow_dispatch:

jobs:

  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: dependencies
        run: |
          python -m pip install -U pip wheel setuptools
      - name: wheel
        run: |
          python -m pip install -e .[tests]
      - name: flake8
        run: |
          flake8 pytiled_parser
      - name: mypy
        run: |
          mypy pytiled_parser
      - name: black
        run: |
          black pytiled_parser --check
      